default_platform(:ios)

platform :ios do
  lane :build_and_upload do |options|
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"]
    )

    match(
      type: "appstore",
      app_identifier: "dev.chilusoft.stratego",
      api_key: api_key,
      readonly: !options[:first_run]
    )

    gym(
      scheme: "Runner",
      export_method: "app-store",
      clean: true
    )

    pilot(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      distribute_external: false
    )
  end
end
