default_platform(:ios)

platform :ios do
  lane :build_and_upload do |options|
    match(
      type: "appstore",
      app_identifier: "dev.chilusoft.stratego",
      username: ENV["APP_STORE_CONNECT_USERNAME"],
      readonly: !options[:first_run]
    )

    gym(
      scheme: "Runner",
      export_method: "app-store",
      clean: true
    )

    pilot(
      skip_waiting_for_build_processing: true,
      distribute_external: false
    )
  end
end
